name: Aimybox android sdk CI

on:
  push:
    branches:
      - master
      - dev
      - release/*
      - feature/*
      - INT-184-github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get secrets for local.properties
        env:
          SECRING_MEM_GPG: ${{ secrets.SECRING_MEM_GPG }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          echo "$SECRING_MEM_GPG" > ./secring-mem.gpg
          echo "$LOCAL_PROPERTIES" > ./local.properties
          echo signing.secretKeyRingFile=${{ github.workspace }}/secring-mem.gpg >> ./local.properties

      - name: Build with gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Publish with gradle
        run: |
          ./gradlew publish