name: Aimybox android sdk CI

on:
  push:
    branches:
      - master
      - dev
      - release/*
      - INT-184-github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: show tasks
        run: |
          ./gradlew tasks --all

      - name: Publish with gradle
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEYID: ${{ secrets.SIGNING_KEYID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SECRING_MEM_GPG: ${{ secrets.SECRING_MEM_GPG }}
        run: |
          echo $SECRING_MEM_GPG > ${{ github.workspace }}/secring-mem.gpg
          echo sonatype.user=$SONATYPE_USER > ${{ github.workspace }}/local.properties
          echo sonatype.password=$SONATYPE_PASSWORD >> ${{ github.workspace }}/local.properties
          echo signing.keyId=$SIGNING_KEYID >> ${{ github.workspace }}/local.properties
          echo signing.password=$SIGNING_PASSWORD >> ${{ github.workspace }}/local.properties
          echo signing.secretKeyRingFile=${{ github.workspace }}/secring-mem.gpg >> ./local.properties
          ls -la ./local.properties

      - name: Get file content
        id: var
        run: echo ::set-output name=local_properties::$(cat ${{ github.workspace }}/local.properties)
      - name: Get output
        run: echo ${{ steps.var.outputs.local_properties }}

#      - name: run task
#        run: |
#          ./gradlew publishDialogflow-apiPublicationToMavenCentralRepository

#      - name: Validate Gradle wrapper
#        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
#
#      - name: Publish packages
#        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
#        with:
#          arguments: publish


#      - name: Publish with gradle
#        run: |
#          ./gradlew publish