name: Aimybox android sdk CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get secrets for local.properties
        run: |
          echo ${{ secrets.SECRING_MEM_GPG }} > ./secring-mem.gpg
          echo ${{ secrets.LOCAL_PROPERTIES }} > ./local.properties
          echo signing.secretKeyRingFile=${{ github.workspace }}/secring-mem.gpg >> ./local.properties

      - name: Build with gradle
        run: |
          chmod +x gradlew
          ./gradlew build