name: Aimybox android sdk CI

on:
  push:
    branches:
      - master
      - dev
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Publish with gradle
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEYID: ${{ secrets.SIGNING_KEYID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          TOKEN: ${{ secrets.TOKEN }}
          SECRING_GPG: ${{ secrets.SECRING_MEM_GPG }}
        run: |
          printf "%s" "$SECRING_GPG" > ${{ github.workspace }}/secring-mem.gpg
          printf "sonatype.user=$SONATYPE_USER\n" > ${{ github.workspace }}/local.properties
          printf "sonatype.password=$SONATYPE_PASSWORD\n" >> ${{ github.workspace }}/local.properties
          printf "signing.keyId=$SIGNING_KEYID\n" >> ${{ github.workspace }}/local.properties
          printf "signing.password=$SIGNING_PASSWORD\n" >> ${{ github.workspace }}/local.properties
          printf "github.token=$TOKEN\n" >> ${{ github.workspace }}/local.properties
          echo signing.secretKeyRingFile=${{ github.workspace }}/secring-mem.gpg >> ./local.properties
          ./gradlew publishComponentsPublicationToMavenCentralRepository
          ./gradlew publishCorePublicationToMavenCentralRepository
          ./gradlew publishDialogflow-apiPublicationToMavenCentralRepository
          ./gradlew publishDummy-apiPublicationToMavenCentralRepository
          ./gradlew publishGoogle-cloud-speechkitPublicationToMavenCentralRepository
          ./gradlew publishGoogle-platform-speechkitPublicationToMavenCentralRepository
          ./gradlew publishHoundify-speechkitPublicationToMavenCentralRepository
          ./gradlew publishJaicf-apiPublicationToMavenCentralRepository
          ./gradlew publishKaldi-speechkitPublicationToMavenCentralRepository
          ./gradlew publishPocketsphinx-speechkitPublicationToMavenCentralRepository
          ./gradlew publishRasa-apiPublicationToMavenCentralRepository
          ./gradlew publishSnowboy-speechkitPublicationToMavenCentralRepository
          ./gradlew publishYandex-speechkitPublicationToMavenCentralRepository

